catalog/urls.py
from django.conf.urls import url
from . import views

app_name = 'catalog'

urlpatterns = [
    url('home_init/', views.index, name='index'),
    url('hello_user/', views.hello_user, name='hello_user'),
    url(r'home', views.home, name='home'),
    url(r'data_heroe/(?P<personaje>.*)/', views.data_character, name='data_character'),
    #url(r'search/(?P<search>.*)/', views.search_character, name='search_character'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path

# Use include() to add paths from the catalog application
from django.urls import include

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='search')),
    # path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models

# Create your models here.

catalog/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.

from django.http import HttpResponse
from .services import get_username, get_character, search_character

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

# Especifique su propio nombre/ubicación de plantilla
def hello_user(request):

    params = { 'order': 'desc' }

    # convert reponse data into json
    users =  get_username(params)
    #print("🚀 ~ context:", users)

    return render(request, "hello_user.html", {'users': users})


# Pantalla principal
def home(request):
    search = request.GET.get("search")

    characters = {}
    if search is not None:
        characters =  search_character(search=search)

    return render(request, "home.html", {'characters': characters})

# Especifique su propia ruta data_heroe/<personaje>
def data_character(request, personaje):
    print("🚀 ~ data_character:")

    # convert reponse data into json
    data =  get_character(personaje=personaje)
    data_img = data.get("thumbnail")
    type_img = '/portrait_xlarge'
    image = data_img.get("path")  + type_img + '.' + data_img.get("extension")
    #print("🚀 ~ data:", data)

    return render(request, "data_heroe.html", {'data': data, 'image': image})

catalog/templates/data_heroe.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'style_data.css' %}">
        <title>Marvel Api</title>
    </head>
    <body>
        <a href='javascript:history.back()' >
            <i class="bi bi-arrow-left-circle"></i>
            Volver al buscador</a>
        <div class="container-fluid p-3 bg-danger text-white text-center" >
            <img src="https://upload.wikimedia.org/wikipedia/commons/9/90/Marvel_Studios_logo.jpg"
                alt="Marvel_Logo" width="200">
            <img src="{% static 'imgs/deadpool3.jpg' %}" alt="Deadpool 3" width="200">
            <h1>El personaje es {{ data.name }}</h1>
        </div>

        <div class="container mt-5">
            <table class="table">
                <thead>
                    <tr>
                        <th> Descripción </th>
                        <th> Imagen </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <p>{{ data.description }}</p>
                        </td>
                        <td> <img src="{{ image }}" alt=""> </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>

catalog/templates/hello_user.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
          <title>User Api</title>
    </head>
    <body>
        <div class="container-fluid p-2 bg-primary text-white text-center">
            <h1>Users</h1>
        </div>
        <div class="container mt-5">
            <table class="table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{ user.name.title }}</td>
                        <td>{{ user.name.first }}</td>
                        <td>{{ user.name.last }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
       </div>
    </body>
</html>

catalog/templates/home.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
          <title>Marvel Api</title>
    </head>
    <body>
        <div class="container-fluid p-2 text-white text-center">
            <!-- <img src="https://upload.wikimedia.org/wikipedia/commons/b/b9/Marvel_Logo.svg"
                alt="Marvel_Logo" width="200">
             -->
            <form class="mt-3" action="{% url 'search:home' %}" method="GET">
                <input name="search" type="text" placeholder="Buscar personaje...">
            </form>
        </div>
        <div class="container mt-5">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Descripción</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ch in characters %}
                    <tr>
                        <td>{{ ch.id }}</td>
                        <td>
                            <a href='data_heroe/{{ch.name}}' >{{ ch.name }}</a>
                        </td>
                        <td>{{ ch.description }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
       </div>
    </body>
</html>